apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pea-nut.fullname" . }}
  labels:
    {{- include "pea-nut.labels" . | nindent 4 }}
type: Opaque
data:
  webPassword: {{ .Values.secrets.WEB_PASSWORD | b64enc | quote }}
  {{- if .Values.secrets.INFLUX_TOKEN }}
  influxToken: {{ .Values.secrets.INFLUX_TOKEN | b64enc | quote }}
  {{- end }}
