name: Setup
description: Install pnpm + Node, and install dependencies (frozen lockfile).

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v6
      with:
        version: latest

    - uses: actions/setup-node@v6.4.0
      with:
        node-version: 24
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm i --frozen-lockfile
