services:
  nut-upsd:
    image: instantlinux/nut-upsd
    container_name: nut-upsd
    devices:
      - /dev/bus/usb
    restart: unless-stopped

  peanut:
    image: brandawg93/peanut:latest
    container_name: PeaNUT
    volumes:
      - ${PWD}/config:/config
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - WEB_PORT=8080

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-storage:/prometheus
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped

volumes:
  prometheus-storage:
  grafana-storage:

networks:
  default:
    name: nut_network
