apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    database: telegraf
    isDefault:
    editable: false
    url: http://influxdb:8086
    jsonData:
      httpMode: GET
