{
 "title": "PeaNUT",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "device", "label": "Device", "query": { "query": "label_values(ups)" } }
  ]
 },
 "panels": [
  {
   "title": "Battery Charge",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ups_battery_charge{ups=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPS Load",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ups_ups_load{ups=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ups_battery_runtime{ups=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}